baseURL = 'https://luisgpat.github.io'
languageCode = 'en-us'
title = 'luisgpat.github.io'
theme = 'hugo-coder'

[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20
[[menus.main]]
    name = 'CV'
    url = '/cv.pdf'
    weight = 30
    [menus.main.params]
      rel = 'internal'