baseURL = 'https://luisgpat.github.io'
languageCode = 'en-us'
title = 'luisgpat.github.io'
theme = 'ananke'

[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'Products'
    pageRef = '/products'
    weight = 20
[[menus.main]]
    name = 'Services'
    pageRef = '/services'
    weight = 30

[[menus.footer]]
    name = 'Terms'
    pageRef = '/terms'
    weight = 10
[[menus.footer]]
    name = 'Privacy'
    pageRef = '/privacy'
    weight = 20