baseURL = 'https://luisgpat.github.io'
languageCode = 'en-us'
title = 'luisgpat.github.io'
theme = 'ananke'

[menus]
[[menus.main]]
    name = 'Products'
    pageRef = '/products'
    weight = 10
[[menus.main]]
    name = 'Hardware'
    pageRef = '/products/hardware'
    parent = 'Products'
    weight = 1
[[menus.main]]
    name = 'Software'
    pageRef = '/products/software'
    parent = 'Products'
    weight = 2
[[menus.main]]
    name = 'Services'
    pageRef = '/services'
    weight = 20
[[menus.main]]
    name = 'CV'
    pre = '<i class="fa-regular fa-heart"></i>'
    url = '/CV.pdf'
    weight = 30
    [menus.main.params]
      rel = 'internal'

[[menus.footer]]
    name = 'Terms'
    pageRef = '/terms'
    weight = 10
[[menus.footer]]
    name = 'Privacy'
    pageRef = '/privacy'
    weight = 20