baseURL = 'https://luisgpat.github.io'
languageCode = 'en-us'
title = 'Luigo'
theme = 'hugo-coder'

defaultcontentlanguage = "en"

paginate = 20


[markup.highlight]
style = "github-dark"

[params]
  author = "Luis Gonzalo Patiño Uribe"
  info = "Hardware and Networking Engineer"
  description = "Luis Site"
  keywords = "blog,developer,personal"
  avatarurl = "me.jpg"
  #gravatar = "luisg.pat@gmail.com"


  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/luisgpat"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/luisg-pat"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 2
  url = "Projects/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"